apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-toleration-mutating-webhook
webhooks:
  - name: pod-toleration-mutating-webhook.kube-system.svc
    clientConfig:
      caBundle: <ca base64>
      url: scheme://host:port/path
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        pod-toleration-injection: enabled
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: 5